version: '3.8'

services:
  nginx:
    image: 'nginx:latest'
    container_name: api-nginx-laravel
    ports:
      - '8090:80'
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
      - '.:/app'
    networks:
      - local
    depends_on:
      - php82

  php82:
    container_name: api-php82-laravel
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_STAGE: 'dev'
    volumes:
      - '.:/app'
    networks:
      - local
    ports:
      - '9000:9000'

  mysql:
    image: 'mysql:5.7'
    container_name: api-mysql-laravel
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql:/docker-entrypoint-initdb.d'
    networks:
      - local

networks:
  local:
    driver: bridge
